name: 'Baseline Action'
description: 'Enforce web platform feature compatibility standards in CI/CD with official Baseline queries support'
author: 'Sheldon Aristide'
branding:
  icon: 'shield'
  color: 'green'

inputs:
  baseline-threshold:
    description: 'Minimum Baseline status required (limited|newly|widely)'
    required: false
    default: 'newly'
  
  include-patterns:
    description: 'File patterns to analyze'
    required: false
    default: '**/*.{js,jsx,ts,tsx,css,scss,html}'
  
  exclude-patterns:
    description: 'File patterns to ignore'
    required: false
    default: 'node_modules/**,dist/**,build/**'
  
  scan-mode:
    description: 'Scan scope mode (auto|diff|repo) - auto detects changed files in PR, diff only changed files, repo scans all files'
    required: false
    default: 'auto'
  
  enforcement-mode:
    description: 'Enforcement level (warn|error|block)'
    required: false
    default: 'error'
  
  max-violations:
    description: 'Maximum number of violations before failing'
    required: false
    default: '0'
  
  browserslist-config:
    description: 'Path to browserslist config file'
    required: false
    default: ''
  
  comment-on-pr:
    description: 'Whether to post detailed PR comments'
    required: false
    default: 'true'
  
  fail-on-new-only:
    description: 'Fail on newly introduced violations only'
    required: false
    default: 'false'
  
  config-path:
    description: 'Path to Baseline configuration file'
    required: false
    default: '.baseline.json'
  
  github-token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  
  output-format:
    description: 'Output format for reports (json|markdown|sarif)'
    required: false
    default: 'json'
  
  sarif-output:
    description: 'Path to write SARIF output for GitHub Advanced Security'
    required: false
    default: ''

  scenario-label:
    description: 'Optional label to distinguish multiple Baseline runs (e.g., strict-demo, passing-demo)'
    required: false
    default: ''

outputs:
  violations-count:
    description: 'Number of compliance violations found'
  
  compliance-score:
    description: 'Percentage of features meeting baseline requirements'
  
  has-violations:
    description: 'Whether violations were found (true/false)'
  
  report-path:
    description: 'Path to the generated report file'
  
  sarif-path:
    description: 'Path to the generated SARIF file (if sarif-output was specified)'
  scenario-label:
    description: 'Echoes the provided scenario label for multi-job demo coordination'

runs:
  using: 'node20'
  main: 'dist/index.js'